version: '3'
services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile 
        environment:
            NODE_ENV: prod
        command: bash -c "npm run typeorm migration:run && npm run serve"
        ports: 
            - "3333:3333"
        depends_on: 
            - db
    db:
        build:
            context: .
            dockerfile: db.dockerfile
