version: '3'
services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile 
        command: sh -c "/usr/local/bin/migration.sh && npm run dev:server"
        ports: 
            - "3333:3333"
        depends_on: 
            - db
        networks:
            - default
    db:
        build:
            context: .
            dockerfile: db.dockerfile
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DATABASE: av2
        networks:
            - default
